name 'sample-app'
maintainer 'XPeppers'
maintainer_email 'devops@xpeppers.com'
license 'all_rights'
description 'Installs/Configures a sample app'
long_description 'Installs/Configures sample app'
version '0.1.0'

depends 'java', '~> 1.39.0'
depends 'maven', '~> 2.1.1'
depends 'mysql', '~> 6.1.2'
depends 'mysql2_chef_gem', '~> 1.0.2'
depends 'database', '~> 4.0.9'
