Vagrant.configure('2') do |config|

  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = 'sample-app-berkshelf'
  config.vm.box_check_update = false
  config.vm.network :private_network, ip: '192.168.33.101'

  config.berkshelf.enabled = false

  if Vagrant.has_plugin?("vagrant-omnibus")
    config.omnibus.chef_version = 'latest'
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
    config.cache.auto_detect = false
    config.cache.enable :yum
    config.cache.enable :gem
    config.cache.enable :chef_gem
    config.cache.enable :generic, { :cache_dir => "/var/chef/cache" }
  end

end
